### ISSUE TITLE
Publish on https://packagist.org for easy composer installation

### ISSUE THREAD

**Issue by evilebottnawi** [wp-cli/profile-command#136]

**Comment by danielbachhuber** [comment]
Out of curiosity, have you tried `wp package install wp-cli/profile-command` ?

**Comment by evilebottnawi** [comment]
@danielbachhuber yep, all work fine, but our CI testing on linux and window, be good install all packages from packagegist without extra scripts.

**Comment by danielbachhuber** [comment]
Sounds good. Here you go: https://packagist.org/packages/wp-cli/profile-command
