### ISSUE TITLE
Can `wp profile` be run as a logged in user?

### ISSUE THREAD

**Issue by Flimm** [wp-cli/profile-command#143]
It would be useful for my use-cases if I could run `wp profile` as a logged in user, as a lot of new functionality is triggered for logged in users.

Could I request this feature? (I'm not sure if it exists already.)

**Comment by danielbachhuber** [comment]
Hi @Flimm,

You can set execution of any WP-CLI command to a specific user with `--user=<user>`. See [global config](https://make.wordpress.org/cli/handbook/config/#global-parameters) for more details.

**Comment by Flimm** [comment]
Amazing, thank you as always @danielbachhuber !
