### ISSUE TITLE
Invalid field: callback_count with --format=json and --fields not specified

### ISSUE THREAD

**Issue by randstring** [wp-cli/profile-command#152]
Running wp_profile on any stage or --all with JSON or CSV output format results in the following error:

> Error: Invalid field: callback_count

Other output formats like 'table' or 'yaml' work just fine. Specifying individual fields with --fields= also works, unless the problematic 'callback_count' field is requested.

PHP version:    5.6.38
WP-CLI version: 2.0.1

**Comment by swang-va** [comment]
The `runcommand\Profile\Logger` class missed a property:
```
public $callback_count	= 0;
```
