### ISSUE TITLE
Installation error: Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by yogeshbeniwal** [wp-cli/profile-command#164]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

Installation is failing with error: `Your requirements could not be resolved to an installable set of packages.`

**Describe how other contributors can replicate this bug**

- wp cli update
- wp package install git@github.com:wp-cli/profile-command.git

**Describe what you would expect as the correct outcome**

Installation of package should be successful, as similar way to install other packages is working fine.

**Let us know what environment you are running this on**

```
OS:     Linux 5.4.0-71-generic #79-Ubuntu SMP Wed Mar 24 10:56:57 UTC 2021 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.16
php.ini used:   /etc/php/7.4/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /home/user
WP-CLI packages dir:    /home/user/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0
```

**Provide additional context/Screenshots**

Error screenshot with details as shown below:

![Screenshot](https://user-images.githubusercontent.com/7325107/115423412-61ed3e80-a230-11eb-9b5a-2661a6047fe0.png)

**Comment by robin-scott** [comment]
Also experiencing this in a couple of places. Also php7.4 - my case Ubuntu 20.04 clean install, with usual necessary dependencies installed.

**Comment by schlessera** [comment]
Current development version of `wp-cli/profile-command` is not compatible with WP-CLI v2.4.0.

Please use the following command instead to install the latest stable version of `wp-cli/profile-command` instead:

```bash
wp package install wp-cli/server-command:@stable
```

**Comment by swissspidy** [comment]
Seems like this issue was resolved, closing for now!
