### ISSUE TITLE
broken link on readme

### ISSUE THREAD

**Issue by leonstafford** [wp-cli/profile-command#168]
## Bug Report

**Describe the current, buggy behavior**

[profiling a WP REST API response](https://runcommand.io/to/profile-wp-rest-api/) leads to a "coming soon" page

**Describe how other contributors can replicate this bug**

 - visit https://github.com/wp-cli/profile-command/
 - click on _profiling a WP REST API response_

**Comment by danielbachhuber** [comment]
Thanks for the report, @leonstafford !
