### ISSUE TITLE
Getting "fatal: No such remote 'composer'" while installing this command

### ISSUE THREAD

**Issue by buntybuddyboss** [wp-cli/profile-command#169]
I am getting this error while installing this. Am I doing something wrong? 

![image](https://user-images.githubusercontent.com/61768860/123757675-d8b35180-d8db-11eb-933c-7d552c9a82c3.png)

**Comment by leonstafford** [comment]
Looks like you used the git URL vs the package name when installing?

How about this:

`wp package install wp-cli/profile-command` to install latest stable.

**Comment by buntybuddyboss** [comment]
@leonstafford 

Actually I was trying different things. I followed as shown here https://github.com/wp-cli/profile-command#installing
But getting the same error.

**Comment by leonstafford** [comment]
@buntybuddyboss sorry, I didn't read it properly. I've tried all variations to install, also on mac OS (11.4, M1).

Could you please share your `~/.wp-cli/packages/composer.json` - maybe has some clues as to the missing remote.

**Comment by leonstafford** [comment]
I noticed my git ref used in the installation looked different than yours. Maybe can also delete the Composer cache and the vendor dir that's being used and try again with the `wp package install https://github.com/wp-cli/profile-command.git`
