### ISSUE TITLE
SSL certificate problem on install.

### ISSUE THREAD

**Issue by marekmaurizio** [wp-cli/profile-command#172]
When trying to install i get this:

Error: curl error 60 while downloading https://wp-cli.org/package-index/packages.json: SSL certificate problem: certificate has expired

**Comment by danielbachhuber** [comment]
Thanks for the report, @marekmaurizio !

SSL certificate looks fine at the moment:

<img width="882" alt="image" src="https://user-images.githubusercontent.com/36432/182884266-e69fc8ef-1481-4c4d-8fe6-b8f63e7ca3ed.png">

Feel free to re-open if you're still experiencing issues.

**Comment by nielslange** [comment]
Hello @danielbachhuber 👋

When running `wp package install wp-cli/profile-command:@stable` and `wp package install wp-cli/profile-command:dev-master` on my MBP 15" (Mid 2015 with Intel i7), no error appears. However, when running the same commands on my MBP 14" (2021 with M1), I'm getting the same error message.

I'm unable to reopen this issue. Could you please reopen it and let me know if I can provide any further information to narrow down this problem?

**Comment by wojsmol** [comment]
Hi @marekmaurizio 
Please post version of Mac OS on the laptop with issue. This is most likely related to expiration of the old Let's Encrypt Root certificate - see [this](https://community.letsencrypt.org/t/os-x-10-11-clients-not-connecting-to-site-with-lets-encrypt-certificates/161576) topic on the LE forum.

**Comment by danielbachhuber** [comment]
@wojsmol Apparently that particular cert wasn't the issue for @nielslange 

Do you know of any diagnostic approach he could use to find the right certificate?

**Comment by wojsmol** [comment]
@danielbachhuber I'm not a Mac expert but reading linked topic from LE forum this problem will occur on OS X 10.11 and earlier. In the mentioned topic the are some solutions to install new LE root certificate on old OS X .

**Comment by danielbachhuber** [comment]
Thanks @wojsmol !

An update to report: @nielslange was able to "fix" this issue by switching from Local to Laravel Valet.

Generally, it seems like a certificate issue on the system, though — not a WP-CLI specific problem.

**Comment by hirasso** [comment]
I was getting the same error for quite some time already. 

In my case, my system's `/private/etc/ssl/cert.pem` was actually **not** expired. But it wasn't being used by my command line PHP version! I am using [MAMP](https://www.mamp.info/de/mac/) and finally solved this error by following [these instructions on SO](https://stackoverflow.com/questions/67228537/mamp-local-development-curl-error-60-ssl-certificate-unable-to-get-local-iss/69630750#69630750).

Now it works without errors! 🍰
