### ISSUE TITLE
Description missing for "wp profile" Command

### ISSUE THREAD

**Issue by mehrazmorshed** [wp-cli/profile-command#177]
Description missing for "wp profile" Command in the table of WP-CLI Commands.
Page Link: https://developer.wordpress.org/cli/commands/

![WPWPWPCapture](https://user-images.githubusercontent.com/22143433/216605280-fa44afa9-f4ea-4ab5-8fae-03699a5b80d9.png)

**Comment by danielbachhuber** [comment]
Thanks @mehrazmorshed !

Closing in favor of https://github.com/wp-cli/handbook/issues/436
